# Generated by Django 6.0.3 on 2026-07-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('portada_url', models.URLField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('payhip_url', models.URLField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
    ]
