# Generated by Django 6.0.3 on 2026-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='epub_filename',
            field=models.CharField(blank=True, help_text='Nombre del archivo EPUB original', max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='folder_name',
            field=models.CharField(blank=True, help_text='Nombre de la carpeta en distribucion', max_length=255),
        ),
    ]
