# Generated by Django 6.0.3 on 2026-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_libro_epub_filename_libro_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
