# Generated by Django 6.0.3 on 2026-07-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payhipclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoría del libro para filtrar en la tienda', max_length=120),
        ),
    ]
