# Generated by Django 6.0.3 on 2026-07-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Parte importante del libro para destacar en el detalle'),
        ),
        migrations.AddField(
            model_name='libro',
            name='pdf_url',
            field=models.CharField(blank=True, help_text='URL pública del PDF para vista previa del libro', max_length=255),
        ),
    ]
