# Generated by Django 6.0.6 on 2026-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_libroview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Alex Goyzueta Delgado', max_length=200)),
                ('titulo', models.CharField(blank=True, help_text='Ej: Analista de datos freelance', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('foto_url', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sobre mí',
                'verbose_name_plural': 'Sobre mí',
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.TextField(blank=True)),
                ('resumen', models.TextField(blank=True, max_length=500)),
                ('imagen_url', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Artículo / Blog',
                'verbose_name_plural': 'Artículos / Blog',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('mensaje_bienvenida', models.TextField(blank=True, help_text='Texto para la sección de contacto')),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Información de contacto',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('plataforma', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, help_text='Enlace al proyecto')),
                ('tecnologias', models.CharField(blank=True, help_text='Separadas por coma', max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS o emoji', max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: LinkedIn, GitHub', max_length=100)),
                ('url', models.URLField()),
                ('icono', models.CharField(blank=True, help_text='URL del icono o clase CSS', max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, help_text='Ej: Python, Visualización, etc.', max_length=100)),
                ('nivel', models.IntegerField(default=3, help_text='Nivel de 1 a 5')),
                ('icono', models.CharField(blank=True, help_text='URL del icono o clase CSS', max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Herramienta / Skill',
                'verbose_name_plural': 'Herramientas / Skills',
                'ordering': ['orden'],
            },
        ),
    ]
