# Generated by Django 6.0.6 on 2026-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_aboutme_blogarticle_contactinfo_course_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Texto descriptivo del hero', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Texto grande del hero (ej: "Transforma datos en poder")', max_length=300),
        ),
    ]
