# Generated by Django 6.0.6 on 2026-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_aboutme_hero_subtitle_aboutme_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, help_text='Ej: CEO de Empresa X', max_length=200)),
                ('texto', models.TextField(help_text='El testimonio del cliente')),
                ('foto_url', models.CharField(blank=True, max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden'],
            },
        ),
    ]
