# Generated by Django 6.0.6 on 2026-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='epub_archivo',
            field=models.FileField(blank=True, help_text='Subir archivo EPUB directamente', null=True, upload_to='epubs/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='pdf_archivo',
            field=models.FileField(blank=True, help_text='Subir archivo PDF directamente', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
