# Generated by Django 6.0.6 on 2026-06-28 15:40

import django.db.models.deletion
import visor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('author', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='es', max_length=10)),
                ('isbn', models.CharField(blank=True, default='', max_length=30)),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('publication_date', models.CharField(blank=True, default='', max_length=50)),
                ('rights', models.TextField(blank=True, default='')),
                ('epub_file', models.FileField(blank=True, null=True, upload_to=visor.models.epub_file_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=visor.models.epub_cover_path)),
                ('file_size', models.IntegerField(default=0, help_text='Tamaño en bytes')),
                ('word_count', models.IntegerField(default=0, help_text='Número estimado de palabras')),
                ('page_count', models.IntegerField(default=0, help_text='Número estimado de páginas')),
                ('chapter_count', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('reading_time_minutes', models.IntegerField(default=0)),
                ('is_opencode_project', models.BooleanField(default=False, help_text='Creado con opencode')),
                ('opencode_path', models.CharField(blank=True, default='', help_text='Ruta al proyecto opencode', max_length=1000)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('completo', 'Completo'), ('publicado', 'Publicado')], default='completo', max_length=20)),
                ('progress_percentage', models.IntegerField(default=100, help_text='Solo aplica si es proyecto opencode')),
                ('diagnostics', models.TextField(blank=True, default='', help_text='JSON con diagnóstico')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=0)),
                ('current_percent', models.FloatField(default=0.0)),
                ('last_position', models.TextField(blank=True, default='', help_text='CFI o identificador de posición')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='visor.book')),
            ],
            options={
                'verbose_name': 'Progreso de lectura',
                'verbose_name_plural': 'Progresos de lectura',
            },
        ),
    ]
