# Generated by Django 6.0.6 on 2026-06-28 23:54

import visor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_book_is_public_book_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Archivo PDF del libro', null=True, upload_to=visor.models.epub_file_path),
        ),
    ]
