from django.urls import path
from .views import (
    about_edit,
    admin_access,
    admin_logout,
    admin_profile,
    blog_create,
    blog_delete,
    blog_detail,
    blog_list,
    blog_update,
    book_create,
    book_delete,
    book_update,
    comprar_libro,
    contact_edit,
    course_create,
    course_delete,
    course_list,
    course_update,
    detalle_libro,
    home,
    project_create,
    project_delete,
    project_list,
    project_update,
    sections_dashboard,
    service_create,
    service_delete,
    service_list,
    service_update,
    social_create,
    social_delete,
    social_list,
    social_update,
    store_dashboard,
    testimonial_create,
    testimonial_delete,
    testimonial_list,
    testimonial_update,
    tool_create,
    tool_delete,
    tool_list,
    tool_update,
)

urlpatterns = [
    path('', home, name='home'),
    path('admin-entrar/', admin_access, name='admin_access'),
    path('admin-salir/', admin_logout, name='admin_logout'),
    path('dashboard/', store_dashboard, name='store_dashboard'),
    path('dashboard/perfil/', admin_profile, name='admin_profile'),
    path('dashboard/secciones/', sections_dashboard, name='sections_dashboard'),
    path('dashboard/secciones/about/', about_edit, name='about_edit'),
    path('dashboard/secciones/proyectos/', project_list, name='project_list'),
    path('dashboard/secciones/proyectos/crear/', project_create, name='project_create'),
    path('dashboard/secciones/proyectos/<int:pk>/editar/', project_update, name='project_update'),
    path('dashboard/secciones/proyectos/<int:pk>/eliminar/', project_delete, name='project_delete'),
    path('dashboard/secciones/cursos/', course_list, name='course_list'),
    path('dashboard/secciones/cursos/crear/', course_create, name='course_create'),
    path('dashboard/secciones/cursos/<int:pk>/editar/', course_update, name='course_update'),
    path('dashboard/secciones/cursos/<int:pk>/eliminar/', course_delete, name='course_delete'),
    path('dashboard/secciones/herramientas/', tool_list, name='tool_list'),
    path('dashboard/secciones/herramientas/crear/', tool_create, name='tool_create'),
    path('dashboard/secciones/herramientas/<int:pk>/editar/', tool_update, name='tool_update'),
    path('dashboard/secciones/herramientas/<int:pk>/eliminar/', tool_delete, name='tool_delete'),
    path('dashboard/secciones/blog/', blog_list, name='blog_list'),
    path('dashboard/secciones/blog/crear/', blog_create, name='blog_create'),
    path('dashboard/secciones/blog/<int:pk>/editar/', blog_update, name='blog_update'),
    path('dashboard/secciones/blog/<int:pk>/eliminar/', blog_delete, name='blog_delete'),
    path('dashboard/secciones/servicios/', service_list, name='service_list'),
    path('dashboard/secciones/servicios/crear/', service_create, name='service_create'),
    path('dashboard/secciones/servicios/<int:pk>/editar/', service_update, name='service_update'),
    path('dashboard/secciones/servicios/<int:pk>/eliminar/', service_delete, name='service_delete'),
    path('dashboard/secciones/social/', social_list, name='social_list'),
    path('dashboard/secciones/social/crear/', social_create, name='social_create'),
    path('dashboard/secciones/social/<int:pk>/editar/', social_update, name='social_update'),
    path('dashboard/secciones/social/<int:pk>/eliminar/', social_delete, name='social_delete'),
    path('dashboard/secciones/contacto/', contact_edit, name='section_contact'),
    path('dashboard/secciones/testimonios/', testimonial_list, name='testimonial_list'),
    path('dashboard/secciones/testimonios/crear/', testimonial_create, name='testimonial_create'),
    path('dashboard/secciones/testimonios/<int:pk>/editar/', testimonial_update, name='testimonial_update'),
    path('dashboard/secciones/testimonios/<int:pk>/eliminar/', testimonial_delete, name='testimonial_delete'),
    path('blog/<int:pk>/', blog_detail, name='blog_detail'),
    path('dashboard/crear/', book_create, name='book_create'),
    path('dashboard/<int:pk>/editar/', book_update, name='book_update'),
    path('dashboard/<int:pk>/eliminar/', book_delete, name='book_delete'),
    path('libro/<int:pk>/', detalle_libro, name='libro_detalle'),
    path('libro/<int:pk>/comprar/', comprar_libro, name='libro_comprar'),
]
